# Configuración de FireGuard
join-threshold: 5  # Conexiones máximas por minuto antes de bloquear una IP
block-duration-seconds: 60  # Duración del bloqueo temporal en segundos
api-port: 8081  # Puerto para la API HTTP del dashboard
