name: Build and Release FireGuard

on:
  push:
    tags:
      - 'v*' # Solo cuando crees un tag como v0.1, v1.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/fireguard-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}